[package]
name = "rust-disc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
genevo = "0.7"
rand = "0.8.5"
chrono = "0.4.38"